# for PracticeMonitor
# using code generated by https://visualtk.com/

import tkinter as tk
import tkinter.font as tkFont

BG_COLOR = "blue"

class PracticeDisplay():

    def __init__(self):

        root = tk.Tk()
        root.title("Practice Monitor v 0.2")

        width =  1500
        height =  300

        factor = 2.0

        screenwidth = root.winfo_screenwidth()
        screenheight = root.winfo_screenheight()
        alignstr = '%dx%d+%d+%d' % (width, height, (screenwidth - width) / 2, (screenheight - height) / 2)
        root.geometry(alignstr)
        root.resizable(width=False, height=False)

        GLabel_252=tk.Label(root)
        ft = tkFont.Font(family='Times',size=int(10*factor))
        GLabel_252["font"] = ft
        GLabel_252["fg"] = "#333333"
        GLabel_252["justify"] = "center"
        GLabel_252["text"] = "Total time"
        GLabel_252.place(x=60*factor,y=40*factor,width=70*factor,height=25*factor)

        GLabel_694=tk.Label(root)
        ft = tkFont.Font(family='Times',size=int(10*factor))
        GLabel_694["font"] = ft
        GLabel_694["fg"] = "#333333"
        GLabel_694["justify"] = "center"
        GLabel_694["text"] = "Session time"
        GLabel_694.place(x=50*factor,y=120*factor,width=92*factor,height=30*factor)

        # total time display
        label_time_total=tk.Label(root)
        ft = tkFont.Font(family='Helvetica',size=int(70*factor))
        label_time_total["font"] = ft
        label_time_total["fg"] = "#333333"
        label_time_total["justify"] = "center"
        label_time_total["text"] = "00:00:00"
        label_time_total.place(x=280*factor,y=40*factor,width=70*factor,height=25*factor)
        self.label_time_total = label_time_total

        label_time_session = tk.Label(root)
        ft = tkFont.Font(family='Times',size=int(62*factor))
        label_time_session["font"] = ft
        label_time_session["fg"] = "#333333"
        label_time_session["justify"] = "center"
        label_time_session["text"] = "00:00:00"
        label_time_session.place(x=280*factor,y=120*factor,width=70*factor,height=25*factor)
        self.label_time_session = label_time_session

        button_reset = tk.Button(root)
        button_reset["bg"] = "#efefef"
        ft = tkFont.Font(family='Times',size=int(10*factor))
        button_reset["font"] = ft
        button_reset["fg"] = "#000000"
        button_reset["justify"] = "center"
        button_reset["text"] = "Reset"
        button_reset.place(x=500*factor,y=70*factor,width=70*factor,height=25*factor)
        button_reset["command"] = self.reset
        self.button_reset = button_reset

        button_scan = tk.Button(root)
        button_scan["bg"] = "#efefef"
        ft = tkFont.Font(family='Times',size=int(10*factor))
        button_scan["font"] = ft
        button_scan["fg"] = "#000000"
        button_scan["justify"] = "center"
        button_scan["text"] = "Scan"
        button_scan.place(x=500*factor,y=30*factor,width=70*factor,height=25*factor)
        button_scan["command"] = self.scan
        self.button_scan = button_scan


        button_export = tk.Button(root)
        button_export["bg"] = "#efefef"
        ft = tkFont.Font(family='Times',size=int(10*factor))
        button_export["font"] = ft
        button_export["fg"] = "#000000"
        button_export["justify"] = "center"
        button_export["text"] = "Export"
        button_export.place(x=500*factor,y=110*factor,width=70*factor,height=25*factor)
        button_export["command"] = self.export
        self.button_export = button_export

        label_sessions = tk.Label(root)
        ft = tkFont.Font(family='Times',size=int(10*factor))
        label_sessions["font"] = ft
        label_sessions["fg"] = "#333333"
        label_sessions["justify"] = "center"
        label_sessions["text"] = "sessions"
        label_sessions.place(x=180*factor,y=180*factor,width=70*factor,height=25*factor)
        self.label_sessions = label_sessions


        label_notes=tk.Label(root)
        ft = tkFont.Font(family='Times',size=int(10*factor))
        label_notes["font"] = ft
        label_notes["fg"] = "#333333"
        label_notes["justify"] = "center"
        label_notes["text"] = "notes"
        label_notes.place(x=180*factor,y=220*factor,width=70*factor,height=25*factor)
        self.label_notes = label_notes

        self.root = root
        # end __init__

    def scan(self):
        print("scan!")

    def export(self):
        print("export")

    def reset(self):
        print("reset")


    def get_root(self):
        return self.root
    
    def set_time_total(self, label_string):
        self.label_time_total["text"] = label_string

    def set_time_session(self, label_string):
        self.label_time_session["text"] = label_string

    def set_time_session_fg(self, str_color):
        self.label_time_session["fg"] = str_color

    def set_session_label(self, label_string):
        self.label_sessions["text"] = label_string

    def set_notes_label(self, label_string):
        self.label_notes["text"] = label_string

